### ISSUE TITLE
Where to start? (number 1 from #36)

### ISSUE THREAD

**Issue by biometrician** [jrckln/Bendyourspline#39]
Number 1 from #36 :

For a first-time user it is not immediately clear that one has to click on Methods. Everything looks really nice, but "Methods" has to be highlighted somehow. Or simply add to the Note, that one can start by clicking on "Methods".

Lena's reply:
I can insert a button with 'Start' or something similar which redirects to 'Methods' tab

**Comment by biometrician** [comment]
I think this is a good idea.

**Comment by ljiricka** [comment]
see c9a6720
