### ISSUE TITLE
Tour button is "hidden" (number 2 from #36)

### ISSUE THREAD

**Issue by biometrician** [jrckln/Bendyourspline#40]
First part of number 2 from #36 :

2) Compared to my first version from last year it is much more complicated (which is per se not bad). But already for the simple version the feedback was "a guide is needed" Here it is even more important. It took me something like 10 minutes to see the "Tour" button. Why not add a "Note" like on the first screen with a comment, that first-time users should take a short tour by clicking on ... .

Lena's reply:
I'll increase the font size of the Tour button, however I would not suggest to make the button bigger since the navbar would then need to be bigger as well.

**Comment by biometrician** [comment]
I am not sure if a bigger font size solves the issue (at least for me). When I am looking at a new page, I look at first in the middle and on the left side (as the text usually starts there). However, I usually do not look at the right corner. I understand that for everyone who has used the app already this button is not necessary. However, most future users will be first-time users. So we have to make their lives easy. 

As some suggestions: We can either put the TOUR button between "BEND YOUR (SP)LINE!" and "home" or (which is more complicated and maybe annoying to experienced users) highlight the TOUR button with a box which appears (like on the welcome screen) and states that "first time users are welcome to take a tour through the app first".

**Comment by ljiricka** [comment]
tour button was removed as discussed last week, see 8c4afb4
