### ISSUE TITLE
Explanation tab (number 2 from #36)

### ISSUE THREAD

**Issue by biometrician** [jrckln/Bendyourspline#41]
Second part of number 2 from #36 :

In my simple app I added an explanation tab, where the 3 methods were explained. I think such a text should be added as well. Currently there is only a list of further references.

Lena's reply:
In a previous discussion we decided to state the references where the methods are described and not to repeat what is written in there.
We could add an explanation in the Tour, please give suggestions to extend the Tour.

**Comment by biometrician** [comment]
Maybe we can discuss that all together. 
If the goal of the app is some self-directed learning, then I think we need some explanations. The target audience of the app will not read these statistical texts. Most will not be able to understand them fully. 
If the app is intended to be used in a teaching setup, then an explanation is not really required. But I think the app is too good to be reduced to this small task. 

If the others agree: As a suggestion, could you add a new "explanation" tab in the app and I draft the text and include it?

**Comment by ljiricka** [comment]
discussed last week: we included help icons (see 0bb6321 and 6bc9dc0) and an explanation tab (see 254df9a)
