### ISSUE TITLE
Navigation through the TOUR (number 9 from #36)

### ISSUE THREAD

**Issue by biometrician** [jrckln/Bendyourspline#43]
Number 9 from#36:

9) For the tour is it possible to use the keyboard (intuitively blank) for "Next"? Currently, one has to play catch the "next" button with the mouse, which is inconvenient. 

Lena's reply: I'll look into it

**Comment by ljiricka** [comment]
it was possible at least for Chrome, Safari, Edge and firefox however Tour button was removed see 8c4afb4
