### ISSUE TITLE
adjust automatically (number 10 from #36)

### ISSUE THREAD

**Issue by biometrician** [jrckln/Bendyourspline#54]
Number 10 from #36 :

I am not sure if I understand the "adjust automatically" button for the intercept correctly. I would assume if I click on it that the intercept will be adjusted automatically. 
But if I use for FPs "set optimal fit" => "adjust automatically". I would expect that nothing happens. However, now the intercept is set to 60. If I click on "adjust automatically" again nothing happens. 

Lena's reply:  I'll look into it

**Comment by ljiricka** [comment]
has been corrected
